[[plugins]]
repo = 'Shougo/dein.vim'

[[plugins]]
repo = 'Shougo/deoplete.nvim'

[[plugins]]
repo = 'jacoborus/tender.vim'

[[plugins]]
repo = 'vim-airline/vim-airline'
hook_add = '''
    let g:airline_powerline_fonts = 1
    let g:airline_theme = 'tender'
    let g:airline#extensions#virtualenv#enabled = 1
    set laststatus=2
'''

[[plugins]]
repo = 'scrooloose/nerdtree'

[[plugins]]
repo = 'thinca/vim-quickrun'

[[plugins]]
repo = 'kana/vim-submode'
